"use client";

import { useState, useEffect } from "react";
import { useRouter } from "next/navigation";
import { 
  PackagePlus, Plus, X, Upload, Shield, Truck, Clock, 
  Star, Award, Zap, Heart, ThumbsUp, Wrench, Headphones, 
  RefreshCw, CheckCircle, Settings, Flame, Snowflake, Loader2, type LucideIcon 
} from "lucide-react";

import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { Label } from "@/components/ui/label";
import { Textarea } from "@/components/ui/textarea";
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from "@/components/ui/select";
import { useToast } from "@/hooks/use-toast";

import ImageUpload from "@/components/ImageUpload";

const iconOptions: { name: string; icon: LucideIcon }[] = [
  { name: "Shield", icon: Shield },
  { name: "Truck", icon: Truck },
  { name: "Clock", icon: Clock },
  { name: "Star", icon: Star },
  { name: "Award", icon: Award },
  { name: "Zap", icon: Zap },
  { name: "Heart", icon: Heart },
  { name: "ThumbsUp", icon: ThumbsUp },
  { name: "Wrench", icon: Wrench },
  { name: "Headphones", icon: Headphones },
  { name: "RefreshCw", icon: RefreshCw },
  { name: "CheckCircle", icon: CheckCircle },
  { name: "Settings", icon: Settings },
  { name: "Flame", icon: Flame },
  { name: "Snowflake", icon: Snowflake },
];

const AdminAddProduct = () => {
  const router = useRouter();
  const { toast } = useToast();
  const [loading, setLoading] = useState(false);

  // Dynamic Categories State
  const [categoriesList, setCategoriesList] = useState<any[]>([]);
  const [subCategoriesList, setSubCategoriesList] = useState<any[]>([]);

  const [formData, setFormData] = useState({
    id: "",
    name: "",
    category: "",
    subCategory: "", // Added Sub-Category, Removed Price
    description: "",
  });

  const [features, setFeatures] = useState<string[]>([""]);
  const [specs, setSpecs] = useState<{ key: string; value: string }[]>([{ key: "", value: "" }]);
  const [highlights, setHighlights] = useState<{ icon: string; text: string }[]>([{ icon: "", text: "" }]);
  
  const [image, setImage] = useState<string>(""); 
  const [gallery, setGallery] = useState<string[]>([]);

  // Fetch Categories on Mount
  useEffect(() => {
    fetch("/api/admin/categories")
      .then((res) => res.json())
      .then((data) => {
        if (data.categories) {
          setCategoriesList(data.categories);
        }
      })
      .catch((err) => console.error("Failed to fetch categories", err));
  }, []);

 const handleInputChange = (e: React.ChangeEvent<HTMLInputElement | HTMLTextAreaElement>) => {
    const { name, value } = e.target;
    
    setFormData((prev) => {
      if (name === "name") {
        const autoGeneratedId = value
          .toLowerCase()
          .replace(/[^a-z0-9]+/g, '-')
          .replace(/^-+|-+$/g, ''); 
          
        return { ...prev, name: value, id: autoGeneratedId };
      }
      
      return { ...prev, [name]: value };
    });
  };
  const handleCategoryChange = (val: string) => {
    setFormData((prev) => ({ ...prev, category: val, subCategory: "" }));
    const selectedCat = categoriesList.find((c) => c._id === val);
    if (selectedCat && selectedCat.subCategories) {
      setSubCategoriesList(selectedCat.subCategories);
    } else {
      setSubCategoriesList([]);
    }
  };

  const handleSubmit = async () => {
    if (!formData.id || !formData.name || !image) {
      toast({
        title: "Missing Fields",
        description: "Please fill in all required fields and upload a main image.",
        variant: "destructive",
      });
      return;
    }

    setLoading(true);

    try {
      const formattedSpecs: Record<string, string> = {};
      specs.forEach((s) => {
        if (s.key && s.value) formattedSpecs[s.key] = s.value;
      });

      const payload = {
        ...formData,
        features: features.filter((f) => f.trim() !== ""), 
        specifications: formattedSpecs,
        highlights: highlights.filter((h) => h.text.trim() !== ""),
        image, 
        gallery,
      };

      const res = await fetch("/api/admin/products", {
        method: "POST",
        headers: { "Content-Type": "application/json" },
        body: JSON.stringify(payload),
      });

      const data = await res.json();

      if (!res.ok) {
        throw new Error(data.error || "Something went wrong");
      }

      toast({
        title: "Success!",
        description: "Product created successfully.",
      });

      router.push("/admin/products");
      router.refresh();

    } catch (error: any) {
      toast({
        title: "Error",
        description: error.message,
        variant: "destructive",
      });
    } finally {
      setLoading(false);
    }
  };

  return (
    <div className="space-y-6 max-w-4xl pb-16">
      <div>
        <h1 className="text-2xl font-bold tracking-tight text-gray-900">Add Product</h1>
        <p className="text-muted-foreground text-sm mt-1">Add a new product to your inventory</p>
      </div>

      {/* Basic Info */}
      <Card className="bg-white border-gray-200 shadow-sm">
        <CardHeader className="pb-4">
          <CardTitle className="text-xs font-semibold uppercase tracking-wider flex items-center gap-2 text-muted-foreground">
            <PackagePlus className="w-4 h-4 text-primary" /> Basic Information
          </CardTitle>
        </CardHeader>
        <CardContent className="space-y-5">
          <div className="grid grid-cols-1 md:grid-cols-2 gap-5">
            <div className="space-y-1.5">
  <Label className="text-xs font-medium text-gray-700">Product ID <span className="text-red-500">*</span></Label>
  <Input 
    name="id" 
    value={formData.id} 
    placeholder="Auto-generated from name" 
    className="bg-gray-50 text-gray-500 border-gray-200 cursor-not-allowed"
    readOnly 
    disabled 
  />
</div>
            <div className="space-y-1.5">
              <Label className="text-xs font-medium text-gray-700">Product Name <span className="text-red-500">*</span></Label>
              <Input name="name" value={formData.name} onChange={handleInputChange} placeholder="e.g. Titan MixMaster 3000" className="bg-white text-black border-gray-200" required />
            </div>
            
            {/* Dynamic Category Dropdown */}
            <div className="space-y-1.5">
              <Label className="text-xs font-medium text-gray-700">Category</Label>
              <Select 
                value={formData.category} 
                onValueChange={handleCategoryChange}
              >
                <SelectTrigger className="bg-white text-black border-gray-200">
                  <SelectValue placeholder="Select Category" />
                </SelectTrigger>
                <SelectContent className="bg-black border-gray-200 z-50">
                  {categoriesList.map((cat) => (
                    <SelectItem key={cat._id} value={cat._id}>{cat.name}</SelectItem>
                  ))}
                </SelectContent>
              </Select>
            </div>

            {/* Dynamic Sub-Category Dropdown */}
            <div className="space-y-1.5">
              <Label className="text-xs font-medium text-gray-700">Sub-Category</Label>
              <Select 
                value={formData.subCategory} 
                onValueChange={(val) => setFormData(prev => ({ ...prev, subCategory: val }))}
                disabled={!formData.category || subCategoriesList.length === 0}
              >
                <SelectTrigger className="bg-white text-black border-gray-200">
                  <SelectValue placeholder={subCategoriesList.length === 0 && formData.category ? "No Sub-categories" : "Select Sub-Category"} />
                </SelectTrigger>
                <SelectContent className="bg-black border-gray-200 z-50">
                  {subCategoriesList.map((sub) => (
                    <SelectItem key={sub._id} value={sub._id}>{sub.name}</SelectItem>
                  ))}
                </SelectContent>
              </Select>
            </div>
          </div>
          
          <div className="space-y-1.5">
            <Label className="text-xs font-medium text-gray-700">Description</Label>
            <Textarea name="description" value={formData.description} onChange={handleInputChange} placeholder="Product description..." rows={3} className="bg-white text-black border-gray-200" />
          </div>
        </CardContent>
      </Card>

      {/* Main Image */}
      <Card className="bg-white border-gray-200 shadow-sm">
        <CardHeader className="pb-4">
          <CardTitle className="text-xs font-semibold uppercase tracking-wider flex items-center gap-2 text-muted-foreground">
            <Upload className="w-4 h-4 text-primary" /> Main Image <span className="text-red-500">*</span>
          </CardTitle>
        </CardHeader>
        <CardContent>
          <ImageUpload 
            value={image ? [image] : []} 
            onChange={(url) => setImage(url)}
            onRemove={() => setImage("")}
          />
        </CardContent>
      </Card>

      {/* Gallery Images */}
      <Card className="bg-white border-gray-200 shadow-sm">
        <CardHeader className="pb-4">
          <CardTitle className="text-xs font-semibold uppercase tracking-wider flex items-center gap-2 text-muted-foreground">
            <Plus className="w-4 h-4 text-primary" /> Gallery Images
          </CardTitle>
        </CardHeader>
        <CardContent>
          <ImageUpload 
            value={gallery} 
            onChange={(url) => setGallery((prev) => [...prev, url])}
            onRemove={(url) => setGallery((prev) => prev.filter((img) => img !== url))}
          />
        </CardContent>
      </Card>

      {/* Features */}
      <Card className="bg-white border-gray-200 shadow-sm">
        <CardHeader className="pb-4">
          <CardTitle className="text-xs font-semibold uppercase tracking-wider text-muted-foreground">Features</CardTitle>
        </CardHeader>
        <CardContent className="space-y-3">
          {features.map((f, i) => (
            <div key={i} className="flex gap-2">
              <Input
                value={f}
                onChange={(e) => {
                  const updated = [...features];
                  updated[i] = e.target.value;
                  setFeatures(updated);
                }}
                placeholder={`Feature ${i + 1}, e.g. 5 speed settings`}
                className="bg-white text-black border-gray-200"
              />
              <Button 
                variant="ghost" 
                size="icon" 
                className="shrink-0 text-muted-foreground hover:text-destructive" 
                onClick={() => setFeatures(features.filter((_, index) => index !== i))}
              >
                <X className="w-4 h-4" />
              </Button>
            </div>
          ))}
          <Button 
            variant="outline" 
            size="sm" 
            className="gap-1.5 mt-1 border-gray-200" 
            onClick={() => setFeatures([...features, ""])}
          >
            <Plus className="w-3.5 h-3.5" /> Add Feature
          </Button>
        </CardContent>
      </Card>

      {/* Specifications */}
      <Card className="bg-white border-gray-200 shadow-sm">
        <CardHeader className="pb-4">
          <CardTitle className="text-xs font-semibold uppercase tracking-wider text-muted-foreground">Specifications</CardTitle>
        </CardHeader>
        <CardContent className="space-y-3">
          {specs.map((s, i) => (
            <div key={i} className="flex gap-2">
              <Input
                value={s.key}
                onChange={(e) => {
                  const updated = [...specs];
                  updated[i] = { ...updated[i], key: e.target.value };
                  setSpecs(updated);
                }}
                placeholder="Key"
                className="w-1/3 bg-white text-black border-gray-200"
              />
              <Input
                value={s.value}
                onChange={(e) => {
                  const updated = [...specs];
                  updated[i] = { ...updated[i], value: e.target.value };
                  setSpecs(updated);
                }}
                placeholder="Value"
                className="bg-white text-black border-gray-200"
              />
              <Button 
                variant="ghost" 
                size="icon" 
                className="shrink-0 text-muted-foreground hover:text-destructive" 
                onClick={() => setSpecs(specs.filter((_, index) => index !== i))}
              >
                <X className="w-4 h-4" />
              </Button>
            </div>
          ))}
          <Button 
            variant="outline" 
            size="sm" 
            className="gap-1.5 mt-1 border-gray-200" 
            onClick={() => setSpecs([...specs, { key: "", value: "" }])}
          >
            <Plus className="w-3.5 h-3.5" /> Add Specification
          </Button>
        </CardContent>
      </Card>

      {/* Highlights */}
      <Card className="bg-white border-gray-200 shadow-sm">
        <CardHeader className="pb-4">
          <CardTitle className="text-xs font-semibold uppercase tracking-wider text-muted-foreground">Highlights</CardTitle>
        </CardHeader>
        <CardContent className="space-y-3">
          {highlights.map((h, i) => (
            <div key={i} className="flex gap-2 items-center text-black">
              <Select
                value={h.icon}
                onValueChange={(val) => {
                  const updated = [...highlights];
                  updated[i] = { ...updated[i], icon: val };
                  setHighlights(updated);
                }}
              >
                <SelectTrigger className="w-1/3 bg-white border-gray-200">
                  <SelectValue placeholder="Select icon">
                    {h.icon && (() => {
                      const found = iconOptions.find((o) => o.name === h.icon);
                      if (!found) return h.icon;
                      const IconComp = found.icon;
                      return (
                        <span className="flex items-center gap-2">
                          <IconComp className="w-4 h-4" />
                          <span className="text-sm truncate">{found.name}</span>
                        </span>
                      );
                    })()}
                  </SelectValue>
                </SelectTrigger>
                <SelectContent className="bg-black border-gray-200 z-50">
                  {iconOptions.map((opt) => {
                    const IconComp = opt.icon;
                    return (
                      <SelectItem key={opt.name} value={opt.name}>
                        <span className="flex items-center gap-2">
                          <IconComp className="w-4 h-4" />
                          <span>{opt.name}</span>
                        </span>
                      </SelectItem>
                    );
                  })}
                </SelectContent>
              </Select>
              <Input
                value={h.text}
                onChange={(e) => {
                  const updated = [...highlights];
                  updated[i] = { ...updated[i], text: e.target.value };
                  setHighlights(updated);
                }}
                placeholder="Text, e.g. 2-year warranty"
                className="bg-white text-black border-gray-200"
              />
              <Button 
                variant="ghost" 
                size="icon" 
                className="shrink-0 text-muted-foreground hover:text-destructive" 
                onClick={() => setHighlights(highlights.filter((_, index) => index !== i))}
              >
                <X className="w-4 h-4" />
              </Button>
            </div>
          ))}
          <Button 
            variant="outline" 
            size="sm" 
            className="gap-1.5 mt-1 border-gray-200" 
            onClick={() => setHighlights([...highlights, { icon: "", text: "" }])}
          >
            <Plus className="w-3.5 h-3.5" /> Add Highlight
          </Button>
        </CardContent>
      </Card>

      <div className="flex items-center gap-4 pt-4">
        <Button 
          type="button"
          variant="outline" 
          onClick={() => router.back()}
          className="px-8 border-gray-200 text-white hover:bg-gray-50 hover:text-black"
        >
          Cancel
        </Button>
        <Button 
          type="button"
          size="lg" 
          className="gap-2 px-8 bg-primary hover:bg-primary/90 text-white font-bold" 
          onClick={handleSubmit}
          disabled={loading}
        >
          {loading ? (
            <Loader2 className="w-4 h-4 animate-spin" />
          ) : (
            <PackagePlus className="w-4 h-4" />
          )}
          Add Product
        </Button>
      </div>
    </div>
  );
};

export default AdminAddProduct;