import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "../globals.css";
import NextTopLoader from 'nextjs-toploader';
import { cn } from "@/lib/utils";
import { Toaster } from "@/components/ui/toaster";

import { NextIntlClientProvider } from "next-intl";
import { getMessages, setRequestLocale } from "next-intl/server";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Betterking Kitchen",
  description: "Generated by create next app",
  icons: {
    icon: "/white-logo.png", 
  },
};

export default async function RootLayout({
  children,
  params,
}: Readonly<{
  children: React.ReactNode;
  params: Promise<{ locale: string }>; 
}>) {
  const { locale } = await params;
  
  setRequestLocale(locale);
  
  const messages = await getMessages();

  return (
    <html lang={locale} suppressHydrationWarning>
      <head>
        <link rel="preload" href="/white-logo.png" as="image" type="image/png" />
        <link rel="preload" href="/black-logo.png" as="image" type="image/png" />
      </head>
      <body className={cn(inter.className, "antialiased")} suppressHydrationWarning>
        <NextIntlClientProvider messages={messages} locale={locale}>
          {children}
          <NextTopLoader color="#D4AF37" height={3} showSpinner={false} />
          <Toaster />
        </NextIntlClientProvider>
      </body>
    </html>
  );
}